### ISSUE TITLE
Unable to Build on Arch - Optimization patch problem?

### ISSUE THREAD

**Issue by Grimish-ng** [Frogging-Family/linux-tkg#1008]
*Before reporting an issue, please check for relevant keywords in the issues search bar, including closed issues. The solution to your issue might be there already !*

**Describe the bug**
 - Which OS do you encounter the bug on?
 - A clear and concise description of what the bug is.
 - Attach the contents of your logs folder by drag & dropping each file into this message.
**Special note for Arch users: please run `makepkg [args] | tee shell-output.log` for more logging!**

Using Arch Patches -
Skipping patch more-uarch-for-kernel-6.8rc4==> ERROR: A failure occured in prepare().

**Comment by kamfretoz** [comment]
Not exactly sure if this is the same error but i've been having troubling building the package as well.

fails with:
```
/usr/share/makepkg/util/message.sh: line 69: printf: `B': invalid format character
  -> Skipping patch more-uarches-for-kernel-6.8-rc4==> ERROR: A failure occurred in prepare().
    Aborting...
  -> exit cleanup done
```

**Comment by Grimish-ng** [comment]
Yes it is.

**Comment by 3dmario** [comment]
Same on latest Arch: `6.10.10-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 12 Sep 2024 17:21:02 +0000 x86_64 GNU/Linux`

**Comment by BrickMan240** [comment]
Modifying the /usr/share/makepkg/util/messahe.sh by adding `echo "DEBUG: mesg = '$mesg'"` before the printf statement at line 69, the PKGBUILD prints the message causing the error.
`DEBUG: mesg = 'Skipping patch more-uarches-for-kernel-6.8-rc4%2B.patch...\n         (unavailable for this kernel version)'`
I'm guessing the %2B is being misinterpreted as being a format specifier for printf? I don't know much scripting or C, but that's how far I've gotten.

**Comment by BrickMan240** [comment]
I'll see about trying to make a PR when I have the time, if someone doesn't get to it by then.

**Comment by koeqaife** [comment]
I have the same error

**Comment by BrickMan240** [comment]
Managed to find where the message comes from. Line 698 of linux-tkg-config/prepare. I'll try and find a way to fix that.

**Comment by leChapelierFou-D** [comment]
Thanks BrickMan240
Now I have found a workaround, if you don't need old kernel just delete the many if around 698

**Comment by jnines** [comment]
> Modifying the /usr/share/makepkg/util/message.sh by adding `echo "DEBUG: mesg = '$mesg'"` before the printf statement at line 69, the PKGBUILD prints the message causing the error. `DEBUG: mesg = 'Skipping patch more-uarches-for-kernel-6.8-rc4%2B.patch...\n (unavailable for this kernel version)'` I'm guessing the %2B is being misinterpreted as being a format specifier for printf? I don't know much scripting or C, but that's how far I've gotten.

`%2B` = `+` after being URL encoded, that's (probably) not an issue.  The patches have mostly (all?) changed names.
  https://github.com/graysky2/kernel_compiler_patch/commit/353e327ef7a253720b29a78c5024475bbe0deebe

`more-uarches-for-kernel-6.8-rc4+.patch` is now `more-ISA-levels-and-uarches-for-kernel-6.8-rc4+.patch`

**Comment by BrickMan240** [comment]
@Tk-Glitch That looks good. I gotta ask though, since I don't have much experience. Would adding `tkgpatch=${tkgpatch//%/%%}` such that the _tkg_patcher looks like:
`_tkg_patcher() {
  tkgpatch=tkgpatch//%/%%  #Right here
  if [ -e "$tkgpatch" ] && [[ $(wc -l <"$tkgpatch") -ge 7 ]]; then
    msg2 "$_msg"
    echo -e "### Applying ${tkgpatch##*/}... ###" >> "$_where"/logs/prepare.log.txt
    patch -Np1 -i "$tkgpatch" >> "$_where"/logs/prepare.log.txt || error "An error was encountered applying patches. It was logged to the prepare.log.txt file."
    echo -e "\n" >> "$_where"/logs/prepare.log.txt
  else
    msg2 "Skipping patch ${tkgpatch##*/}...\n         (unavailable for this kernel version)"
  fi
}`
Would this be a good or bad idea? It would catch future '%'s from breaking the script again, but I'm worried it might cause a different issue later on since I don't know much.

**Comment by Tk-Glitch** [comment]
@BrickMan240 No reason for such an issue going forward. The `+` sign was an issue for curl back in the days, resulting in our use of `%2B`, but it isn't anymore so we can directly use the `+` sign now. In the external patches we use, only graysky2's patches are formatted that way so that should be all good. Now in case of external patches that would contain `%2B` using `echo` instead of `msg2` would work too, and prevent more potential issues with printf, also outside of just the `%` sign.
