### ISSUE TITLE
PKGBUILD Fails At The End

### ISSUE THREAD

**Issue by HurricanePootis** [Frogging-Family/linux-tkg#176]
This happened two different Arch Installs on two different machines. Whenever its packaging the kernel, I get these errors:

```
INSTALL sound/xen/snd_xen_front.ko
  INSTALL virt/lib/irqbypass.ko
  DEPMOD  5.10.15-120-tkg-cfspootix
rm: cannot remove '/home/borowski/linux-tkg/pkg/linux510-tkg-cfs/usr/lib/modules/5.10.15-120-tkg-cfs/source': No such file or directory
rm: cannot remove '/home/borowski/linux-tkg/pkg/linux510-tkg-cfs/usr/lib/modules/5.10.15-120-tkg-cfs/build': No such file or directory
==> ERROR: A failure occurred in package_linux510-tkg-cfs().
    Aborting...
  -> exit cleanup done

  -> exit cleanup done

  -> compilation time : 

real    23m3.596s
user    232m54.719s
sys     20m46.325s
borowski@TheCloutPC ~/linux-tkg :( $
```

I am not sure what I am doing wrong, if anything.

**Comment by HurricanePootis** [comment]
Yeah I was doing something wrong, lol

**Comment by Tk-Glitch** [comment]
What were you doing wrong, if I may ask?

**Comment by HurricanePootis** [comment]
I was added a custom name to the end of my kernel, where it would say something like "linux510-tkg-cfs-monke"

**Comment by dhasial** [comment]
I had the same issue just now and this helped me fix it. I was adding another string to the end of the kernel name in menuconfig and after a successful build, the script complained that it could not do `rm "$modulesdir"/{source,build}` (line 166 of the PKGBUILD in `hackbase()`) because it thinks a directory is named one thing and the user appends that string in menuconfig.
