### ISSUE TITLE
Script overwriting the custom kernel .config when call the installer

### ISSUE THREAD

**Issue by bkdwt** [Frogging-Family/linux-tkg#200]
I spent more than 1 hour customizing the kernel directly through menuconfig on linux-src-git and when I called the tkg installer, it overwrote everything and I lost the .config that I had edited. Config.old for some reason has the same settings as the original config.

Is there any way to prevent the installer from overwriting the modified .config manually by me without using the tkg installer? 

```
-> Current branch: * (HEAD detached at v5.10.22)
 -> Reseting files to their original state
HEAD is now at b672142f7 Linux 5.10.22
Removing .config
Removing .config.old
```

EDIT: The same problem happens when I just use the installer without making any changes manually on linux-src-git. My luck now is that I saved the modified .config before trying again. The script did not overwrite the kernel already installed, just stating that it already existed on the system and that it had nothing to do.

**Comment by AdelKS** [comment]
The script cleans what is on `linux-src-git` by design, so it can be reused at each consequent recompile. If you want to use `menuconfig` and co, the script offers to do so at the appropriate time: you have to either set `_menuconfig` in `customization.cfg` or leave it empty and the script will prompt you if you want to use `menuconfig` and co. The changes done in `menuconfig` at that point will stay.
