### ISSUE TITLE
My pc automatically logs out while building this kernel

### ISSUE THREAD

**Issue by ExistingDude** [Frogging-Family/linux-tkg#231]
Hi! I am using Garuda Linux (A distro based on arch linux). And I am trying to compile this kernel. But when I try to compile and answer all questions, it appears to be compiling but then automatically logs me out after 5-10 mins. Then I am unable to log back in. I have tried to compile this 4-5 times and the same behavior happens every time. Any help will be appreciated.
Thanks!

[inxi -Fxxxza](https://bin.garudalinux.org/?048a8853067b25fa#3BGzvojauxXHjao3eAbsxbpcsCivsyUeQUPkSZWNMNxD) output

**Comment by Tk-Glitch** [comment]
Two scenarios are the most probable to me:
  - You (or your distro) have set makepkg to compile packages in `/tmp`, and you don't have enough RAM to store the 22+ GB the kernel needs during compilation on top of your OS and apps running. After attempting to swap for a while, the OOM killer starts nuking critical processes like display-server and friends, resulting in a forced, broken state logout.
  - Your machine is unstable (overclocked?) and/or not properly cooled. Building the kernel is a pretty taxing task and can reveal CPU and/or RAM instabilities, or lead to overheating when the cooler isn't adequate. If your machine is overclocked, reducing your clocks or dropping back to stock is worth a shot.

**Comment by ExistingDude** [comment]
The kernel needs 22GB RAM? I only have 16GB. I wanted the pds kernel as I read that they are the best for gaming on some 1 year old threads but my distro didn't provide them. Only bmq and muqss kernels are there so I tried to compile myself. When I asked the maintainers of Garuda they told me that they didn't package pds as it is not as good and that bmq is better now due to project C so I am now using linux-tkg-bmq kernel and had no issues so far. I am probably not going to try to compile again until I find a kernel even better. Thanks for replying!

**Comment by Tk-Glitch** [comment]
It needs 22+ GB of storage space while compiling. By default, on Archlinux, makepkg uses disk space for that along with a bit of RAM (2-3 GB), but some people like to build in `/tmp` (which uses RAM) for lower SSD writes. Most packages don't need much storage space during compilation so it's rarely an issue on 8GB+ RAM equipped systems. The kernel, though, since 5.8 or so, uses more than 20GB, limiting the above choice to 24GB or more RAM equipped systems.

I don't know if Garuda uses `/tmp` by default, but it might but just that if you didn't change anything yourself.

BMQ isn't as fast as UPDS yet but it's pretty good overall these days, and doesn't suffer from some quirks affecting *some* machines with I/O heavy scenarios. There's also currently a bug with UPDS and suspend that I'll try to fix asap.

**Comment by ExistingDude** [comment]
Ah ok thanks!
