### ISSUE TITLE
Can't load nvidia module with linux57-tkg-MuQSS 5.7.7-16

### ISSUE THREAD

**Issue by z0n** [Frogging-Family/linux-tkg#28]
Hi, I've been using linux56-tkg-MuQSS on Arch Linux in the past. However, linux57-tkg-MuQSS doesn't load my nvidia module anymore. I've tried the nvidia-dkms package and the nvidia-dkms-tkg package but both show this error during boot in dmesg:
`module: x86/modules: Skipping invalid relocation target, existing value is nonzero for type 1, loc 000000001c5c7c4d, val ffffffffc0a4d179`

Here are my [linux](https://pastebin.com/Vst07Naw) and [nvidia](https://pastebin.com/8rhSQv5h) configs.

The DKMS modules build just fine for all kernels without any errors.
I'm currently running linux-ck-skylake 5.7.7-1 but other than that nothing special (custom GCC etc). The default Arch 5.7 kernel and the ck kernel boot just fine with the nvidia module.

**Comment by Tk-Glitch** [comment]
Hello!
Interesting issue :frog: As a starting point I'd try again with `_modprobeddb="false"`, as it's a known breaker. Then I'd make sure clang isn't used to build the dkms modules for that kernel since it reportedly leads to that specific result. But since you mentioned that you're using *nothing special* I assume the latter is not something you're attempting.

**Comment by z0n** [comment]
Hi! :frog: 
It seems like I do have _something special_ as I had distcc configured on my system configured in the past. There are [some issues](https://wiki.archlinux.org/index.php/Distcc#Quirks_compiling_the_Arch_Linux_kernel_package) which caused me to disable it but I forgot to disable it in some places. Now that I've completely disabled it the kernel builds fine (and I'm actually running it right now).
Thanks for the help though, I'll close this ticket. :slightly_smiling_face:
