### ISSUE TITLE
Set CCACHE_SLOPPINESS when using ccache

### ISSUE THREAD

**Issue by v1993** [Frogging-Family/linux-tkg#282]
It seems that without `CCACHE_SLOPPINESS=time_macros` set there isn't much speedup when using ccache.

**Comment by AdelKS** [comment]
You mean `time_macros` needs to be removed ? because it's already set for [arch](https://github.com/Frogging-Family/linux-tkg/blob/d7878e7f40ce713a70aef56aa74516d56b8117e5/PKGBUILD#L622)  and in [install.sh](https://github.com/Frogging-Family/linux-tkg/blob/d7878e7f40ce713a70aef56aa74516d56b8117e5/install.sh#L312)

**Comment by AdelKS** [comment]
I will consider this to be fixed as `time_macros`  is indeed used in `CCACHE_SLOPPINESS`
