### ISSUE TITLE
[RPM] It's not recommended to have unversioned Obsoletes: Obsoletes: kernel-headers

### ISSUE THREAD

**Issue by kleinermob** [Frogging-Family/linux-tkg#339]
error: Bad exit status from /var/tmp/rpm-tmp.ifuCtn (%build)

RPM build errors:
    line 20: It's not recommended to have unversioned Obsoletes: Obsoletes: kernel-headers
    Bad exit status from /var/tmp/rpm-tmp.ifuCtn (%build)
make[1]: *** [scripts/Makefile.package:59: rpm-pkg] Fehler 1
make: *** [Makefile:1576: rpm-pkg] Fehler 2

this is the error

[customization.txt](https://github.com/Frogging-Family/linux-tkg/files/7403023/customization.txt)

**Comment by cartesius82** [comment]
```
sudo zypper install -f linux-glibc-devel
```

**Comment by minhtricute69** [comment]
I have known the reason why in OpenSUSE Tumbleweed this issue happenned. Because the diffierent between version of the newest **linux-glibc-devel** aka kernel-headers use for kernel development and the newest default linux kernel. In my system, the default linux kernel is version **"kernel-default-5.14.14-1.3.x86_64"** but the kernel-headers just at version **"linux-glibc-devel-5.14-1.2.x86_64"** so this mismatch make rpm package manager can't fínd the exact kernel-headers using for compile kernel. This is what i've found in my system. Hope you guys can fix it soon or the OpenSUSE team will make an update for the kernel-headers asap.

**Comment by minhtricute69** [comment]
> I have known the reason why in OpenSUSE Tumbleweed this issue happenned. Because the diffierent between version of the newest **linux-glibc-devel** aka kernel-headers use for kernel development and the newest default linux kernel. In my system, the default linux kernel is version **"kernel-default-5.14.14-1.3.x86_64"** but the kernel-headers just at version **"linux-glibc-devel-5.14-1.2.x86_64"** so this mismatch make rpm package manager can't fínd the exact kernel-headers using for compile kernel. This is what i've found in my system. Hope you guys can fix it soon or the OpenSUSE team will make an update for the kernel-headers asap.

And this is the reason why the warning was thrown when compile kernel on OpenSUSE Tumbleweed

**Comment by AdelKS** [comment]
I am not sure I understand, the `install.sh` script at the end produces `linux-glibc-devel`, `linux-headers` and `linux-image` (I don't remember the exact naming scheme) packages. Why does it need anything from what's installed ?

**Comment by minhtricute69** [comment]
> I am not sure I understand, the `install.sh` script at the end produces `linux-glibc-devel`, `linux-headers` and `linux-image` (I don't remember the exact naming scheme) packages. Why does it need anything from what's installed ? And it does it through the means of `make rpm-pkg` within the kernel sources folder.

Oh, i forgot this aspect, sorry for my bad English. In both OpenSUSE Tumbleweed and Leap, the kernel has been seperated into 2 package **kernel-default** (contain kernel and its modules)  and **linux-glibc-devel**(aka kernel-header). According to what i have found in the OpenSUSE wiki, linux-glibc-devel is a package that: "**_provides Linux kernel headers, the kernel API description required for compilation of almost all programs. This is the userspace interface; compiling external kernel modules requires kernel-(flavor)-devel, or kernel-syms to pull in all kernel-*-devel, packages, instead._**". So it is and compulsory dependencies you've to get in your OpenSUSE to compile all programs and custom kernel too. Though the install.sh script has build linux-glibc-devel at the end but without linux-glibc-devel preinstalled in your system you couldn't be able to compile or make anything with rpmbuild. So this is the reason why i told you about this problem caused by linux-glibc-devel. If you don't have it you cannot compile or make anything with rpmbuild.

**Comment by AdelKS** [comment]
> Oh, i forgot this aspect, sorry for my bad English.

Oh not at all, it just that the issue at hand is rather complex :p

> the kernel API description required for compilation of almost all programs

This absolutely true, the only exception is the kernel source code itself: it is entirely self-sufficient and I believe it can be compiled on Windows (that obviously does not have the kernel headers) if one wishes so.

Now, about `linux-glibc-devel`. There are two messages you are conveying

> but without linux-glibc-devel preinstalled in your system you couldn't be able to compile or make anything with rpmbuild

That has an easy fix: install `linux-glibc-devel` with the other needed dependencies before compiling the kernel. The issue is with what follows:

> this problem caused by mismatching version between kernel-default and linux-glibc-devel

If successfully built, `linux-tkg` replaces the `linux-glibc-devel` package, which means it will always mismatch with `kernel-default` and everyone will hit against this issue when recompiling ?

**Comment by minhtricute69** [comment]
> > Oh, i forgot this aspect, sorry for my bad English.
> 
> Oh not at all, it just that the issue at hand is rather complex :p
> 
> > the kernel API description required for compilation of almost all programs
> 
> This absolutely true, the only exception is the kernel source code itself: it is entirely self-sufficient and I believe it can be compiled on Windows (that obviously does not have the kernel headers) if one wishes so.
> 
> Now, about `linux-glibc-devel`. There are two messages you are conveying
> 
> > but without linux-glibc-devel preinstalled in your system you couldn't be able to compile or make anything with rpmbuild
> 
> That has an easy fix: install `linux-glibc-devel` with the other needed dependencies before compiling the kernel. The issue is with what follows:
> 
> > this problem caused by mismatching version between kernel-default and linux-glibc-devel
> 
> If successfully built, `linux-tkg` replaces the `linux-glibc-devel` package, which means it will always mismatch with `kernel-default` and everyone will hit against this issue when recompiling ?

Absolutely not, i have found the exact reason why and now i've to collect evidence to check again my idea.

**Comment by minhtricute69** [comment]
So i have found the exact reason, not belong to the kernel-default and linux-glibc-devel as i said before, it just the problem between glibc and kernel header( linux-glibc-devel). As you know, glibc belong to the compiler toolchain, which is used to compile other program and it is linked with the kernel-header through Linked Library, that will provide "instruction" for compiler to work. In Linux, the compiler toolchain will link with a kernel-header that it compiled again. So if you use kernel-default, that has been compiled against with the glibc in your system and its kernel-header has been linked with glibc. The problem is when you compiled custom kernel, you replaced old header with your new ones, it will automatically linked with the existing compiler in your OS, and it will work with default kernel and compiler in that system because it was compiled against by the old kernel-header and compiler(glibc) so it compatible with both kernels of your system. Because of the exist kernel-header in OpenSUSE Tumbleweed was compile with a different glibc version so it wasn't linked correctly to the compiler in your system, it will linked with the compiler it was compiled with. This is where the problem occured, you compiled custom kernel, rpm will use compiler and it will find which kernel header was compiled against and  linked with it for instruction if not it will show us warning about unversioned kernel-header because it is not linked with that header so it cannot build corectly. 

Next if you replace a linux-glibc-devel package of linux-tkg it will work for both kernel and linked correctly with the existing compiler in your OS. Because it was compiled with default kernel-header and compiler in system, it will compatible with default kernel and custom kernel too. So don't worry about it will break system.

**Comment by minhtricute69** [comment]
The problem is the kernel-header and kernel-default not use the same compiler to build so it cause the problem unversioned kernel-header when compiler run and find instruction

**Comment by minhtricute69** [comment]
After a kernel update, the problem has been fixed and can build linux-tkg rpm properly, but the warning still there ...
![Screenshot at 2021-11-15 11-00-35](https://user-images.githubusercontent.com/42957778/141741868-6928ddd7-cfe9-463d-b143-789dde7a09ba.png)
![Screenshot at 2021-11-15 10-32-09](https://user-images.githubusercontent.com/42957778/141741876-bfc48dfd-aa1f-4f73-b344-4b7211daff60.png)
![Screenshot at 2021-11-15 10-29-55](https://user-images.githubusercontent.com/42957778/141741882-6b5bb760-0151-4a8a-bdf8-02ccc1439acb.png)

**Comment by AdelKS** [comment]
I am sorry but I cannot understand how to properly fix this problem, what do you suggest ?

**Comment by yousha97** [comment]
in my case had to install all dependencies `warning: line 19: It's not recommended to have unversioned Obsoletes: Obsoletes: httpd-suexec
warning: line 34: It's not recommended to have unversioned Obsoletes: Obsoletes: secureweb-devel, apache-devel
warning: line 51: It's not recommended to have unversioned Obsoletes: Obsoletes: secureweb-manual, apache-manual
Wrote: /root/rpmbuild/SRPMS/httpd-2.4.54-1.src.rpm

RPM build warnings:
    line 19: It's not recommended to have unversioned Obsoletes: Obsoletes: httpd-suexec
    line 34: It's not recommended to have unversioned Obsoletes: Obsoletes: secureweb-devel, apache-devel
    line 51: It's not recommended to have unversioned Obsoletes: Obsoletes: secureweb-manual, apache-manual
[yousharashid@yousha-rashid Downloads]$ sudo rpmbuild -tb httpd-2.4.54.tar.bz2
warning: line 19: It's not recommended to have unversioned Obsoletes: Obsoletes: httpd-suexec
warning: line 34: It's not recommended to have unversioned Obsoletes: Obsoletes: secureweb-devel, apache-devel
warning: line 51: It's not recommended to have unversioned Obsoletes: Obsoletes: secureweb-manual, apache-manual
error: Failed build dependencies:
	apr-devel >= 1.4.0 is needed by httpd-2.4.54-1.x86_64
	apr-util-devel >= 1.4.0 is needed by httpd-2.4.54-1.x86_64
	libselinux-devel is needed by httpd-2.4.54-1.x86_64
	libuuid-devel is needed by httpd-2.4.54-1.x86_64
	libxml2-devel is needed by httpd-2.4.54-1.x86_64
	lua-devel is needed by httpd-2.4.54-1.x86_64
	openldap-devel is needed by httpd-2.4.54-1.x86_64
	pcre-devel >= 5.0 is needed by httpd-2.4.54-1.x86_64
	zlib-devel is needed by httpd-2.4.54-1.x86_64

RPM build warnings:
    line 19: It's not recommended to have unversioned Obsoletes: Obsoletes: httpd-suexec
    line 34: It's not recommended to have unversioned Obsoletes: Obsoletes: secureweb-devel, apache-devel
    line 51: It's not recommended to have unversioned Obsoletes: Obsoletes: secureweb-manual, apache-manual
`
