### ISSUE TITLE
Latest update (rel 248) causes graphical glitches / display issues (nvidia)

### ISSUE THREAD

**Issue by jeois** [Frogging-Family/linux-tkg#481]
I upgraded linux-tkg-bmq (5.17.0-247 -> **5.17.0-248**), and after I reboot the graphics are illegible and super dark. The only objects visible are traces of outlines in barely visible colors.

This seems like a Nvidia graphics driver issue.  Thanks to tkg's `nvidia-all`, I got the latest proprietary drivers 510.60.02. I tried reinstalling both the tkg kernel and nvidia drivers, but it still displays a screen tear during boot and then darkness when X starts.

Fortunately, I had a different kernel, also 5.17, which I'm using right now with the same DKMS modules and _no issues_.  Therefore, we know this driver _does_ work, just not with the tkg kernel.  I'm not sure where to start with configuration.  The defaults always worked fine before.

Afterwards, I tried tracing the boot journal, but warning and error messages related to graphics between the one that works and tkg-bmq are the same.  So according to systemd, the nvidia drivers are indeed being loaded, but it's functioning as if in some kind of failed state.  I tried loading the drivers early with initramfs, but the results are the same.  The non-tkg 5.17 kernel works, and I've been rebooting repeatedly trying to get the tkg kernel to display correctly.  

Anybody have an ideas?  Thanks in advance.

**Comment by jnines** [comment]
Had essentially the same issue, completely black screen with a cursor.  Odd thing was I could still log in, open a terminal via shortcut and reboot.  The really odd thing was I had no tty (so no ctrl+alt+F*).  Had to remove `nvidia-drm.modeset=1` from boot parameters to get it functioning again.

**Comment by Edu4rdSHL** [comment]
I confirm that https://github.com/Frogging-Family/linux-tkg/commit/19dda36dea731f944fbcb11d30123f59150af089 fix the problem. Maybe putting a comment on that parameter would be a good idea to avoid further breakages.

**Comment by jeois** [comment]
Looked like several toggled parameters from #476 Arch 5.17 config might impact this, so I was having trouble pinpointing it.
Thanks for fixing it already, so we don't have go through trial and error.

...closing the issue, resolved.

**Comment by Tk-Glitch** [comment]
> I confirm that [19dda36](https://github.com/Frogging-Family/linux-tkg/commit/19dda36dea731f944fbcb11d30123f59150af089) fix the problem. Maybe putting a comment on that parameter would be a good idea to avoid further breakages.

We could enforce it through the config script instead of allowing the defconfig to change it, but I'm kinda curious about why Arch upstream re-enabled that after it broke Nvidia drivers last time (when they enabled it in 5.16 testing release). They will probably fix it before it lands in stable by still weird.

**Comment by Edu4rdSHL** [comment]
> > I confirm that [19dda36](https://github.com/Frogging-Family/linux-tkg/commit/19dda36dea731f944fbcb11d30123f59150af089) fix the problem. Maybe putting a comment on that parameter would be a good idea to avoid further breakages.
> 
> We could enforce it through the config script instead of allowing the defconfig to change it, but I'm kinda curious about why Arch upstream re-enabled that after it broke Nvidia drivers last time (when they enabled it in 5.16 testing release). They will probably fix it before it lands in stable by still weird.

I was checking the commits, seems that it was enabled [just now in 5.17](https://github.com/archlinux/svntogit-packages/commit/7f98cfac6f93f0c57b930d42da2f95e77076fbc4#diff-6503b30d816e211d1909eed3e1eff5f9105fdc48f5735921a59f4906f99415beR2288), I checked [the 5.16 update](https://github.com/archlinux/svntogit-packages/commit/94f84e1ad8a530e54aa34cadbaa76e8dcc439d10#diff-6503b30d816e211d1909eed3e1eff5f9105fdc48f5735921a59f4906f99415beR2273) and it was disabled there, the problem was [with 5.15](https://bugs.archlinux.org/task/72645).

Looks like it's going to be disabled on 5.17.1 again as per https://bugs.archlinux.org/task/74203#comment207217

Enforcing it through the config script would be the best way to address this problem.
