### ISSUE TITLE
[Request ] P-State, alternative to ACPI CPUFreq.

### ISSUE THREAD

**Issue by adamgibbo** [Frogging-Family/linux-tkg#486]
Long shot but worth asking.

https://www.phoronix.com/scan.php?page=news_item&px=Linux-5.17-Power-Management

Can this be implemented? Hopefully it wouldn't be too time consuming. I'd happily buy someone a beer for the effort :)

**Comment by adamgibbo** [comment]
Edited for correct link

**Comment by B3HOID** [comment]
It will likely be applied upstream, so there should be an option in the kernel configuration under "Power management" section so if for some reason it's not enabled in the Arch config (which is what linux-tkg pulls from) you can enable it yourself.

**Comment by adamgibbo** [comment]
Sorry, I meant an option within 'customization.cfg' to enable it by default.

**Comment by AdelKS** [comment]
It's already there! Try this: `sudo cpupower frequency-info`. If it doesn't give you amd-pstate as scaling driver, you need to add a kernel command line `amd_pstate.shared_mem=1`, but it has performance issues and that's why it's not enabled by default https://www.kernel.org/doc/html/latest/admin-guide/pm/amd-pstate.html#kernel-module-options-for-amd-pstate

The current consensus afaik is that that driver is a little bit useless for desktop users. Probably more useful for laptops. There was a laptop review on phoronix I believe.

**Comment by adamgibbo** [comment]
Sweet, I'll try it out.

**Comment by Tk-Glitch** [comment]
I have made using the feature easier with https://github.com/Frogging-Family/linux-tkg/commit/b14cca1c5dc3b1e911509062f04737d9c66a344c as Arch's defconfig made it more annoying to access.

**Comment by Tk-Glitch** [comment]
Closing as resolved considering the lack of feedback and the fact that I'm using that feature daily with the `amd_pstate.shared_mem=1` kernel parameter.
