### ISSUE TITLE
5.16 and 5.17 failed to build

### ISSUE THREAD

**Issue by wamuu-sudo** [Frogging-Family/linux-tkg#493]
![unknown](https://user-images.githubusercontent.com/92715832/162561957-2fac7c2b-438f-428f-beca-0a4e80effd71.png)

**Comment by Iglu47** [comment]
hmm, strange. it looks like https://gitlab.com/alfredchen/linux-prjc/-/issues/55
and it really should affect the 5.17 and 5.16 branches (no 5.15 and lower) 
but 5.17 at least should be fixed by https://github.com/Frogging-Family/linux-tkg/commit/30be4c4bc586f2253a040112c2241db42c8d577e#diff-2bc2b8a9bf96f086b7aab42dc938438f8276804df5484fe4ca9d1531d9c64022R9934

**Comment by wamuu-sudo** [comment]
5.16 and 5.17 still not working for me

**Comment by Iglu47** [comment]
well, at least there is clearly the issue with 5.16 in upstream (which apparently has not been reported yet), but I think that this simple fix from 5.17 @Tk-Glitch will quickly add even before waiting for an official fix.

**Comment by Iglu47** [comment]
@wamuu-sudo what build environment/distribution are you using?

**Comment by wamuu-sudo** [comment]
Gentoo of course, with running-kernel parameter.

**Comment by wamuu-sudo** [comment]
5.17.2-cfs works properly

**Comment by wamuu-sudo** [comment]
I've recompile and 5.17.2-pds works now.
I'll check 5.16.19

**Comment by Iglu47** [comment]
> I'll check 5.16.19

probably 5.16 will be built only after the fix from the PR above.
