### ISSUE TITLE
Failing to boot, and when booted using QEMU, "ZSTD-compressed data is corrupt"

### ISSUE THREAD

**Issue by Dhamma-valence** [Frogging-Family/linux-tkg#511]
**Describe the bug**
 - Which OS do you encounter the bug on?
 
Debian Sid

 - A clear and concise description of what the bug is.
 
When installing and booting normally via rEFInd, literally nothing happens when I try to boot into the kernel. Ordinarily, a kernel will say something like "Loaded from EFI boot stub, loading kernel commandline options" and then go further into the boot. With this kernel, *nothing*, just frozen.

When I load it via direct kernel boot in qemu/virt-manager, I at least get an error message which is `ZSTD-compressed data is corrupt -- System halted`.

Normally I'd spend a lot more time debugging something like this before making a bug report, but seeing as how it doesn't even boot, I have very little to go on.

 - Attach the contents of your logs folder by drag & dropping each file into this message.

[customization.cfg.txt](https://github.com/Frogging-Family/linux-tkg/files/8639218/customization.cfg.txt)
[prepare.log.txt](https://github.com/Frogging-Family/linux-tkg/files/8639219/prepare.log.txt)
[shell-output.log.txt](https://github.com/Frogging-Family/linux-tkg/files/8639220/shell-output.log.txt)
[system-info.txt](https://github.com/Frogging-Family/linux-tkg/files/8639221/system-info.txt)

**Comment by rchris494** [comment]
i think the problem is more with debian bookworm/sid and qemu/kvm. i setup my gpu pass-though windows 10 ltsc efi boot kvm/qemu on bullseye with the tkg-pds kernel and have no errors other than the usual boot warnings. the minute i apt update to bookworm/sid i get the same error. except mine will boot into windows 10 ltsc. bookworm/sid has been a trainwreck in some areas. qemu/kvm is one of them. so personally i don't think the problem is kernel related, but that i my opinion on that.

**Comment by Dhamma-valence** [comment]
I would agree if it were only happening on kvm/qemu, but it also happens when booting normally through rEFInd, which is my normal usage. I actually only loaded it into qemu to see if I could get more error messages out of it for debugging.

**Comment by rchris494** [comment]
i use to use rEFInd boot manager until i realized all i needed to do was put the /boot partition & grub on a usb drive and set it to boot first from USB, because my old hp z420, z620 and z840 would not boot off an NVMe drive. in later version of rEFInd i had nothing but problems with it. the 2017 version i had was the only one that seemed to work correctly. so i moved away from rEFInd completely. now i just mbr boot bookworm/sid and do a kvm single gpu passthrough if i want to work on windows (mostly gaming). i pass off all cores and 95% of the memory to kvm. i can barely tell the difference between it and booting into full blown windows. the TKG-PDS kernel helped a lot with lag and gave me better performance.

**Comment by AdelKS** [comment]
Are you using TPM ? Because it will not work if so, I believe.

**Comment by Dhamma-valence** [comment]
I believe TPM is a windows thing, yes? I've never actually installed windows on this machine. And from my searching, it seems TPM and secure boot are mentioned together, and I've explicitly disable secure boot. I've also searched my bios for any mention of TPM and I've seen none.

**Comment by Dhamma-valence** [comment]
So, I've done a rough check with
`sudo dmesg | grep -w tpm`
`lsmod | g tpm`
and both come up totally blank, so it seems as though there is no TPM to speak of.

**Comment by AdelKS** [comment]
Yeah sorry I wasn't clear enough, I asked if you were booting with secure boot enabled. But then again you'd see an error message that your kernel image is not signed. 

I do not know how rEFInd works with .deb packages of kernels, you will have to Google that and you may even consider this unsupported on our side. It works perfectly with official debian kernels ? How does refind detect them ? How is the .deb  produced by Linux-tkg (which simply uses `make deb-pkg`thag is offered by the upstream kernel build system, that may help you find answers).

Keep us updated !

**Comment by rchris494** [comment]
you can try this 5.17.5 tkg-pds kernel. total stock debian build. recommended generic cpu. all recommended default settings. no changes to customization.cfg file. built with gcc 12 on my debian bookworm system up to date as of today 5/7. all 3 debs are included in the tar.gz

https://drive.google.com/file/d/1zIO6Ywl8Bar6T03cqdJ5i1kC87pAOWfe/view?usp=sharing

maybe you had a bad build of the kernel?

I'm lost to why you use rEFInd?  EFI/UEFI secure booting? or using a dual os boot? because really EFI/UEFI is not needed for the average user unless you are securing banking records, financial transactions, a data center server or your own homebrew router. if you're doing any of those a BSD OS is a more hardened kernel / OS than debian and running an enterprise work station or rack server with a hardened bios firmware.

**Comment by Dhamma-valence** [comment]
So - rchris494, the debs you linked to worked for me! I actually went back after and tried it with the same specifications you mentioned, all default settings, etc etc, just kept pressing enter with no changes, and yet it still didn't work :(

I know you said you did no changes to customization.cfg, but is there any file you can provide that I could diff with my own to figure out what the difference is? I'm currently just trying to extract your .debs and mine, and looking for any differences.


To AdelKS, yeah, I've actually never had a linux kernel that didn't work in this way. The official kernels from debian work fine, the unofficial ones from both Xanmod and Liquorix worked just fine. And if something ever broke, it at least had some kind of output. It has never just *completely frozen straight from boot*. rEFInd works in essence like grub does, it automatically makes boot entries whenever a new kernel is installed, or when an initrd or vmlinuz file gets updated/changed. It also allows you to make general boot parameter changes that get applied to its autogenerated boot entries, as well as allowing you to write specific ones for specific kernels if you're so inclined.

**Comment by rchris494** [comment]
this is the command i use to build with
rm -rf linux-tkg (if i have previously build a kernel. i always work with a fresh build directory)

git clone https://github.com/Frogging-Family/linux-tkg.git && cd linux-tkg && ./install.sh install

then i selected the > recommended default. i actually select the number. i don't know if that makes a difference or not.  i did that configuration for the build i linked. i did a generic cpu because i did not know your cpu model and you can't really go wrong with generic cpu. when i build for my system. i actually select the correct cpu model. i doubt there is any performance gains between the actual cpu model vs the generic cpu. the developers here probably could answer that question.

here is a link to the customization.cfg and logs
https://drive.google.com/file/d/1X2HT16L5Api6INtQ_8lco_z-WHwcbpO9/view?usp=sharing

luckily i have not deleted that folder yet. i was about to build the 5.17.6 kernel.

**Comment by Dhamma-valence** [comment]
So - I've recreated my root partition from scratch and tried building this kernel again. It worked flawlessly. I have no clue what was wrong with my system that would cause such an issue, but luckily I still have both the old kernel and root partition. If I get the time, I will compare the extracted vmlinuz of the broken system, the one rchris494 sent me, and the one I've created on the now-working system to see if I can figure out what exactly caused it to break. I'll open another issue should that ever happen. Thanks for all the help you both gave me, I appreciate it.

**Comment by AdelKS** [comment]
>  i doubt there is any performance gains between the actual cpu model vs the generic cpu

Nearly nada, as far as I understand the kernel cannot use SIMD instructions for its own inner workings (except for cryptographical functions). So fine-tuning to your own CPU yields little improvements, that I'd say is equivalent to setting `-mtune=native` (and not `-march=native`)

> rm -rf linux-tkg (if i have previously build a kernel. i always work with a fresh build directory)

Especially if you are using an SSD, I'd avoid doing this. A simple `git reset --hard` inside the linux-tkg folder should suffice. So you keep the `linux-src-git` folder (that is perfectly cleaned between builds, and only incrementally updated for each new kernel version, so a minimum of things get downloaded).

Glad you fixed your issue @Dhamma-valence, yeah don't hesitate to open an issue and maybe someone can help,
