### ISSUE TITLE
Why is CONFIG_RANDOM_TRUST_CPU disabled?

### ISSUE THREAD

**Issue by mabod** [Frogging-Family/linux-tkg#646]
I am just starting to use linux-tkg on EndeavourOS. When comparing kernel config files I realized linux-tkg does not set CONFIG_RANDOM_TRUST_CPU and CONFIG_RANDOM_TRUST_BOOTLOADER.

Other distros like Arch, debian and fedora enable both of them with "y". Why not linux-tkg?

**Comment by Tk-Glitch** [comment]
This can be enabled through the config file : https://github.com/Frogging-Family/linux-tkg/blob/master/customization.cfg#L220
Due to popular demand it was set to disabled by default since enabling it lowers security (RDRAND (Intel) is apparently considered as untrustworthy) for a small to *very* small boot time gain.

**Comment by mabod** [comment]
Thanks for the explanation. I didnt see the option `_random_trust_cpu` at first.

But then, why do the major distros like arch, debian, fedora and opensuse have CONFIG_RANDOM_TRUST_CPU enabled when it is a security issue? 

I believe the security concerns are old and not valid anymore. At least this is my understanding of the history described here:

https://en.wikipedia.org/wiki/RDRAND#Reception

and the patch provided  in October 2013:

https://github.com/torvalds/linux/commit/85a1f77716cf546d9b9c42e2848b5712f51ba1ee

**Comment by Tk-Glitch** [comment]
The security concerns were brought up with 4.19 (introducing the aforementioned RANDOM_TRUST_CPU option) in 2018 and nothing has changed since afaik. See https://www.phoronix.com/news/Linux-Kernel-Q-HW-RNGs. That being said, the choice is more of a political one. Even though it would be a terrible place for a backdoor, RDRAND is a black box nonetheless.

Our users were vocal enough about wanting it disabled when it was introduced that I decided to add a toggle for it in the .cfg. That way people who'd like it enabled could do so "easily" instead of going through manual config. If people didn't care that much we would have used whatever was default on your distro.

**Comment by mabod** [comment]
Thanks for this explanation. I will keep RANDOM_TRUST_CPU enabled.

By the way, even the default kernel is shipping with RANDOM_TRUST_CPU enabled since mid of this year, 2022.

Interesting read on the kernel mailing list:

https://lore.kernel.org/lkml/20220605171539.417872-1-Jason@zx2c4.com/T/

**Comment by Tk-Glitch** [comment]
I'm fine with it. Hopefully there won't be too much critics this time 🐸
