### ISSUE TITLE
What is the correct value for _rr_interval ?

### ISSUE THREAD

**Issue by mabod** [Frogging-Family/linux-tkg#666]
When I check the `customization.cfg` file it says this about _rr_interval:
```
# Round Robin interval is the longest duration two tasks with the same nice level will be delayed for. When CPU time is requested by a task, it receives a time slice equal
# to the rr_interval in addition to a virtual deadline. When using yield_type 2, a low value can help offset the disadvantages of rescheduling a process that has yielded.
# MuQSS default: 6ms"
# PDS default: 4ms"
# BMQ default: 2ms"
# Set to "1" for 2ms, "2" for 4ms, "3" for 6ms, "4" for 8ms, or "default" to keep the chosen scheduler defaults.
_rr_interval=""
```
The possible numeric values for _rr_interval are 1-4.

But when I leave it empty and wait for the prompt during the compilation process I see this: 

```
Round Robin interval is the longest duration two tasks with the same nice level will
    be delayed for. When CPU time is requested by a task, it receives a time slice equal
    to the rr_interval in addition to a virtual deadline. When using yield_type 2, a low
    value can help offset the disadvantages of rescheduling a process that has yielded.
    
        0) 2ms
      > 1) 4ms
        2) 6ms
        3) 8ms
[0-3]: 
```

Here the possible values are 0-3.

What is correct now?

**Comment by Tk-Glitch** [comment]
Both are correct. It might be more confusing since the entries are numbers, but the config file isn't used in the same way as the prompt answers. For example when you set "pds" as your cpu scheduler, you select it with numbers, while in the config file you set "pds" as value for the variable.

For our rr interval case, if the value is set in the .cfg, it'll be multiplied by 2 to set the actual rr interval value, while if it's selected through the prompt it'll go through an array ("2" "4" "6" "8"). The first entry in the array is index 0, the second one is index 1 etc. So in the prompt case, 0 will set "2" as rr interval value, 1 will set "4" and so on.

It used to be different in the selector before we used arrays, and was adapted since while retaining the original values. We *could* simply accept the raw desired value in the .cfg file these days and drop the `_rr_interval=$(($_rr_interval * 2))` processing. It might be less confusing to set 2, 4, 6 or 8 in there instead of the current 1, 2, 3, 4, but the prompt will keep using 0-3 index.

Hope it's clearer now :)

**Comment by mabod** [comment]
Thanks for the explanation. It is much clearer now. I will close it here.
