### ISSUE TITLE
always CONFIG_HZ_250=y and  CONFIG_HZ=250 with _cpusched="bore"

### ISSUE THREAD

**Issue by mabod** [Frogging-Family/linux-tkg#687]
I am currently testing the BORE cpu scheduler.
 I found that my timer setting `_timer_freq="500"` is being ignored when I select  `_cpusched="bore"`. The timing will always be

```
CONFIG_HZ_250=y 
CONFIG_HZ=250
```

This is true for kernel 6.1 and 6.0 on EndeavourOS.
Why is that?

**Comment by mabod** [comment]
I digged more into this. I search the kernel source code for some hints - after all customizations and patches have been applied. 

I found that with  `_cpusched="bore"` I get:

```
./include/generated/autoconf.h:#define CONFIG_HZ_250 1
./include/generated/autoconf.h:#define CONFIG_HZ 250
./include/config/auto.conf:CONFIG_HZ_250=y
./include/config/auto.conf:CONFIG_HZ=250](url)
```

while with `_cpusched="cfs"` (my default) I get:


```
./include/generated/autoconf.h:#define CONFIG_HZ 500
./include/generated/autoconf.h:#define CONFIG_HZ_500 1
./include/config/auto.conf:CONFIG_HZ=500
./include/config/auto.conf:CONFIG_HZ_500=y
```

The customization.cfg file is the same in both cases, except for the   `_cpusched` setting.

**Comment by Tk-Glitch** [comment]
Since 500 is unavailable by default, we need to patch it in. It looks like we stopped doing that along the way for the "CFS tweaks" schedulers (namely cacule, tt and bore). 500 and 750 values were falling back to 250 as a result. Other values were fine, so since we're defaulting to 1000 these days it hopefully didn't affect too many users.
