### ISSUE TITLE
6.5 kernel not building

### ISSUE THREAD

**Issue by faptaincrunch** [Frogging-Family/linux-tkg#804]
**Describe the bug**

- Which OS do you encounter the bug on? **Ubuntu 23.04**

When trying to build kernel 6.5 it fails to build. Was able to build this kernel 2 days ago perfectly fine. Attached are the log files.

[customization.cfg.txt](https://github.com/Frogging-Family/linux-tkg/files/12497827/customization.cfg.txt)
[prepare.log.txt](https://github.com/Frogging-Family/linux-tkg/files/12497828/prepare.log.txt)
[shell-output.log.txt](https://github.com/Frogging-Family/linux-tkg/files/12497829/shell-output.log.txt)
[system-info.txt](https://github.com/Frogging-Family/linux-tkg/files/12497830/system-info.txt)

**Comment by Tk-Glitch** [comment]
Thanks! SSL fun it is :D

**Comment by Tk-Glitch** [comment]
Seems to be this https://lore.kernel.org/lkml/3bc6a541-dd00-61b3-b8f7-d35d09965654@alu.unizg.hr/T/

We already had such a workaround in place but it was only triggered when using either a hardened config or no config. Since you have `_configfile="linux-tkg-config/6.5/config.x86_64"` set in your .cfg, it didn't trigger.
I changed it slightly so it'll now trigger anyway as long as you're targeting debian/ubuntu.

https://github.com/Frogging-Family/linux-tkg/commit/8b578cde89d2111d185130ed9047d8b8006b1597

Please test it out to confirm it fixed the issue.

**Comment by faptaincrunch** [comment]
Fixed the issue and compiled perfectly. Closing issue, thanks!

**Comment by Tk-Glitch** [comment]
:frog: :+1:
