### ISSUE TITLE
[Feature Request] Select GPU drivers to build

### ISSUE THREAD

**Issue by almostalive** [Frogging-Family/linux-tkg#808]
Seeing the new "_kernel_on_diet" got me thinking. Why not add an option to select which GPU drivers to build (default all). This could be something to use with and without "_kernel_on_diet".

I imagine it something like this

Default
_gpu_drivers="amdgpu,i915,nouveau,radeon" (assuming this kernel is only used for x86_64 PC's)

So someone with an all newer amd can easily just build amdgpu only. Then any sorts of combinations that people may have.

I went with this suggestion because I think most users of this kernel will find it useful, be there kernel on a diet or not. Probably would have to ignore this option though if a user is using modprobedb since that would already have the gpu driver they want.

I also had an idea of two new userconfig files. One for adding weight to the kernel, only useful with kernel on diet. For users that kernel on diet fits 99% of their needs but also need that one or more extra modules for themselves. The other is for removing weight from the kernel. That one could be useful for both diet and non-diet. For users that know for certain they don't need those modules with kernel on diet or want a full kernel without those modules. I guess these could also be used with modprobedb but wouldn't make sense.

Thanks for reading and the hard work you all put into this making it the best custom kernel.

**Comment by AdelKS** [comment]
Hello,

Thanks for your feedback!

Adding` kernel_on_diet` will already add maintenance burden and adding complexity will only make it worse x)

On the other hand, kernel_on_diet option does NOT affect kernel performance, just
- how much space it takes when compiling and when installed
- how time it takes to build
Since kernel_on_diet already drastically reduces both of those, adding tweaks to the list isn't very useful. I suppose it could save a minute of compile time for those who don't want AMD GPU, and a few megabytes of space. Not really worth it. Kernel_on_diet so far reduces the list of built modules by nearly 90%, we probably will need to populate it more to fit with everyone's hardware. Except if it's like very specific I think.
