### ISSUE TITLE
NUMA disabled gives: get_mempolicy: Function not implemented

### ISSUE THREAD

**Issue by mabod** [Frogging-Family/linux-tkg#873]
I am using Endavouros.
I set `_numadisable="true"` for all my kernels. In this case with 6.6.12. Today a new firmware package was installed:

```
linux-firmware 20240115.9b6d0b08-1
linux-firmware-whence 20240115.9b6d0b08-1
```

and with that I see several messages like `get_mempolicy: Function not implemented`. I see those messages in the journal or, for example, when I start zsh or bash. Compiling the kernel with  `_numadisable="false"` removes these messages.

I do not know if that is serious or not, but I thought I better mention it here.

**Comment by mk-fg** [comment]
Running gdb with breakpoint on get_mempolicy points to syscall.c file in numactl project, which is used by multiple tools via libnuma.so (e.g. loaded by "ps" from procps-ng dynamically as `dlopen("libnuma.so", RTLD_LAZY)` if it is present).
Warning seem to be issued on library init, so printed by all tools that happen to load that .so file in any way.

Seem to be fixed in upstream git here - https://github.com/numactl/numactl/issues/212 - so should probably go away after 2.0.18 or later numactl release.

**Comment by mabod** [comment]
Thanks for this info. So it is not a firmware issue as I thought it was, but it is an issue with the numactl package 2.0.17 which happens to be updated at the same time as the firmware (18. January). I would want to remove the numactl package but is a dependency of fio. Waiting for a new numactl package now. But the release cycle is very slow. This can take a year.

**Comment by mabod** [comment]
New `numactl 2.0.18` arrived today.  And it fixes this "`get_mempolicy: Function not implemented`" messages.
