### ISSUE TITLE
linux57-rc-tkg Cannot boot

### ISSUE THREAD

**Issue by NastySpaghetti** [Frogging-Family/linux-tkg#9]
I first tried to use linux57-rc-tkg with native Arch nvidia-dkms, dkms failed to apply nvidia for linux57.
I then tried to use nvidia-all with the patch kernel override "5.7". It got detected by dkms.

I then, after running the command mkinitcpio -p linux and regenerating the grub.cfg, tried to boot using linux57, it failed saying it doesn't find the mountpoint of my linux partition and then it entered in rescue mode(can't provide precise log).
I can boot perfectly fine using linux56-tkg or using the arch native kernel

Link to the customization.cfg of linux57-tkg. [https://pastebin.com/2Ve0vF5g](https://pastebin.com/2Ve0vF5g)
Link to the customization.cfg of nvidia-all. [https://pastebin.com/w5VdbjRX](https://pastebin.com/w5VdbjRX)

After consideration it may not be related to nvidia directly

**Comment by Tk-Glitch** [comment]
> I first tried to use linux57-rc-tkg with native Arch nvidia-dkms, dkms failed to apply nvidia for linux57.

That's expected, nvidia doesn't provide a 5.7 compatible driver at this point in time.

> I then tried to use nvidia-all with the patch kernel override "5.7". It got detected by dkms.

The override isn't supposed to be used that way on a normal, end-user setup. You supposedly want to let the script do its job at detecting what patch(es) your setup actually requires (with no override), though that's not the cause of your issue.
Note: You *need* to have the kernels you want to build against already installed so they are found by the script and the driver gets patched accordingly.

> I then, after running the command mkinitcpio -p linux and regenerating the grub.cfg, tried to boot using linux57, it failed saying it doesn't find the mountpoint of my linux partition and then it entered in rescue mode(can't provide precise log).

Actual logs would have been useful here for sure 😄 However, that points to an issue that has nothing to do with the nvidia driver indeed. Since I'm noticing you have `_modprobeddb="true"` in your config, I'll pretty confidently say that's the root cause of your issue. Missing mountpoint while you know it's there and works with a different kernel is a sign of a missing driver, which modprobed-db will cause more often than not. Turning that option off will likely get you a working setup on 5.7rc.

**Comment by NastySpaghetti** [comment]
I'll try that and I'll tell you.
Thank you

**Comment by HougeLangley** [comment]
Nvidia Vulkan Dev have a try ?

**Comment by Tk-Glitch** [comment]
?

**Comment by NastySpaghetti** [comment]
Right now, it's compilling. But I had try installing nvidia vulkan-dev on linux56-tkg but the performances were horrendous

**Comment by Tk-Glitch** [comment]
Since this is not a nvidia driver related issue 🐸

**Comment by NastySpaghetti** [comment]
So it does indeed work with modprobedb sets to false. Hooray!
![image](https://user-images.githubusercontent.com/32963491/81959882-6c5e8b80-9610-11ea-9906-e69c92fa3efc.png)

I don't know if it's worth making an issue thread but with every nvidia-tkg versions I used, in the "PowerMizer" tab I can set up the preffered usage mode but I cannot overclock/underclock the GPU, it let me inputs number but pressing enter doesn't register the change. I'm sure there is a way to modifiy it with the command "
nvidia-settings" itself, but it seems way too tedious.
![image](https://user-images.githubusercontent.com/32963491/81960348-1fc78000-9611-11ea-9355-330b8f5d2faa.png)

**Comment by Tk-Glitch** [comment]
You can try the following:
```
nvidia-settings -a [gpu:0]/GPUGraphicsClockOffset[1]=0 # replace with desired offset
nvidia-settings -a [gpu:0]/GPUMemoryTransferRateOffset[1]=0 # replace with desired offset
```
This is what I used to do for my Nvidia GPUs with success.

I'm unfamiliar with such a card with only two power levels, and 0 not being the highest one.. That's very unlikely to be my bug though. The only thing related in nvidia-all is the coolbits option:
```
# Coolbits value - Enables fan control & overclocking from nvidia-settings - A value of 31 enables all features
_coolbits="31"
```
Maybe your specific GPU doesn't like that 31 value (which was supposed to work for every GPU available, legacy as well).

**Comment by NastySpaghetti** [comment]
The thing is, it does work with native Arch nvidia-settings with coolbits at 31

**Comment by Tk-Glitch** [comment]
I'm not seeing anything out of the ordinary there. But yes if there's an issue with this I'd like to fix it for sure, and I invite you to open an issue for nvidia-all. Arch's package doesn't enable coolbits by default so it might be due to the way I'm doing it.. Possibly a race condition of some sort.

**Comment by NastySpaghetti** [comment]
Issue reguardind Linux57-rc-tkg is solved.
