### ISSUE TITLE
Failed to set APST feature

### ISSUE THREAD

**Issue by Myew420** [Frogging-Family/linux-tkg#953]
I can't help but notice a particular message during boot, that being
`[    2.018711] nvme nvme0: failed to set APST feature (2)`

I would just like to add that I don't know what APST does and whether it's important, but seeing as this doesn't happen on the zen kernel, I thought I should let y'all know.
OS: Arch
SSD: Kingston A1000
[dmesg.txt](https://github.com/user-attachments/files/15550750/dmesg.txt)

**Comment by BillFleming** [comment]
That is a power saving feature of SSDs. Just because there is no warning doesn't mean the feature is working or enabled in older kernels. (many SSDs can't do it) Maybe the warning message is brand new. Note that framework ships WD_BLACK 4TB SN850X specifically because it has APST support if you want a recommendation. About to install one of those drives also into my desktop PC.

**Comment by Tk-Glitch** [comment]
Not an issue from us. Closing.
