### ISSUE TITLE
No Qualcomm Atheros Driver QCA9377

### ISSUE THREAD

**Issue by NextGenOP** [Frogging-Family/linux-tkg#969]
OS: Debian 13
Kernel: v6.9.9 from releases
Problem: Wi-Fi not working.
output of `lspci -k`
```
01:00.0 Network controller: Qualcomm Atheros QCA9377 802.11ac Wireless Network Adapter (rev 31)
	Subsystem: AzureWave Device 2a51
```
i already have linux firmware and atheros firmware installed (its working with other kernel).
output of `sudo modprobe ath10k_pci`
`modprobe: FATAL: Module ath10k_pci not found in directory /lib/modules/6.9.8-tkg-bore`

**Comment by Tk-Glitch** [comment]
The releases are "minimal" and many modules are stripped out due to github actions storage constraints. Adding ath10k module in there should be fine on our end, but you might want to build your own (since local builds have "full" config) to have all the modules you may need as you could stumble upon another module missing from those.

**Comment by NextGenOP** [comment]
thanks for the clarification, i think i'll close this issue.
